#!/usr/bin/env bash
#
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx restart