#!/usr/bin/env bash
#
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend localnodes
    bind *:80
    mode http
    default_backend nodes
    backend nodes
    mode http
    balance roundrobin
    server 1277-web-01 35.196.87.82:80 check weight 50
    server 1277-web-02 54.146.203.53:80 check weight 50
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart