#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=0
while [[ i -le 9 ]]
do
    if [[ i -eq 7 ]]
    then
	echo 'good luck'
    elif [[ i -eq 3 ]]
    then
       echo 'bad luck'
    else
    	echo 'Holberton School' 
    fi
    ((i++))
done
